### ISSUE TITLE
Add a Code of Conduct for Contributors 

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/jabong-scraper#2]
* Add a new file called Code of Conduct for new contributors as to how to write code to the repository.

**This Issue is open up for grabs only for first timers who haven't sent a PR yet! If you have already sent a PR, kindly avoid resolving this Issue! The Issue can be claimed by mentioning "I Claim!" in the comments below!**

**Comment by strongdan** [comment]
I have contributed once elsewhere, so I will refrain from working on this issue, but I would like to help with the main code when it's available.

**Comment by sbshah97** [comment]
Please do! The main code is available currently! Create an Issue for an improvement that you'd like to do and claim the Issue and you'll be assigned it! No Problems there!

As a matter of fact you can create an Issue to implement threading for the Scraper!

**Comment by strongdan** [comment]
Thanks, but I think that's way beyond my capabilities. All I know is that you import the threading module, but I don't know how to use it.

**Comment by sbshah97** [comment]
Hey, I'd suggest try! It's something new that you'd learn. I built this piece of code by googling for a couple of hours and then getting the right answer! Before that I didn't know head or tail of the code! 

If you're stuck somewhere we can always talk, but that's how you'll learn, that's the whole purpose of this according to me! 

Let me know what you decide finally! Cheers!

**Comment by strongdan** [comment]
Okay, sounds good. I'll give it a shot!

**Comment by devAmoghS** [comment]
"I Claim" This is my first time in Hacktoberfest and wish to get my hands dirty. Please let me know if i can be of some help.

**Comment by sbshah97** [comment]
Fair Point haven't yet recieved a PR from @strongdan Issue assigned to @devAmoghS
